import { connect } from 'react-redux'
import Map from '../ui/Map'

// TODO: load this from the server

const AIRPORT_COORDINATES = {
    'DEN' : {
        "id": 3486,
        "ident": "KDEN",
        "type": "large_airport",
        "name": "Denver International Airport",
        "latitude_deg": 39.861698150635,
        "longitude_deg": -104.672996521,
        "elevation_ft": 5431,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-CO",
        "municipality": "Denver",
        "scheduled_service": "yes",
        "gps_code": "KDEN",
        "iata_code": "DEN",
        "local_code": "DEN",
        "home_link": "http://www.flydenver.com/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Denver_International_Airport",
        "keywords": "DVX, KVDX"
    },
    'SEA':   {
        "id": 3875,
        "ident": "KSEA",
        "type": "large_airport",
        "name": "Seattle Tacoma International Airport",
        "latitude_deg": 47.44900131225586,
        "longitude_deg": -122.30899810791016,
        "elevation_ft": 433,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-WA",
        "municipality": "Seattle",
        "scheduled_service": "yes",
        "gps_code": "KSEA",
        "iata_code": "SEA",
        "local_code": "SEA",
        "home_link": "http://www.portseattle.org/seatac/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Seattle-Tacoma_International_Airport",
        "keywords": ""
    },
    'ATL':   {
        "id": 3384,
        "ident": "KATL",
        "type": "large_airport",
        "name": "Hartsfield Jackson Atlanta International Airport",
        "latitude_deg": 33.63669967651367,
        "longitude_deg": -84.4281005859375,
        "elevation_ft": 1026,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-GA",
        "municipality": "Atlanta",
        "scheduled_service": "yes",
        "gps_code": "KATL",
        "iata_code": "ATL",
        "local_code": "ATL",
        "home_link": "http://www.atlanta-airport.com/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Hartsfield-Jackson_Atlanta_International_Airport",
        "keywords": ""
    },
    'MCO':   {
        "id": 3670,
        "ident": "KMCO",
        "type": "large_airport",
        "name": "Orlando International Airport",
        "latitude_deg": 28.429399490356445,
        "longitude_deg": -81.30899810791016,
        "elevation_ft": 96,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-FL",
        "municipality": "Orlando",
        "scheduled_service": "yes",
        "gps_code": "KMCO",
        "iata_code": "MCO",
        "local_code": "MCO",
        "home_link": "http://www.orlandoairports.net/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Orlando_International_Airport",
        "keywords": "Disney World,Epcot Center"
    },
    'ORD':   {
        "id": 3754,
        "ident": "KORD",
        "type": "large_airport",
        "name": "Chicago O'Hare International Airport",
        "latitude_deg": 41.97859955,
        "longitude_deg": -87.90480042,
        "elevation_ft": 672,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-IL",
        "municipality": "Chicago",
        "scheduled_service": "yes",
        "gps_code": "KORD",
        "iata_code": "ORD",
        "local_code": "ORD",
        "home_link": "http://www.flychicago.com/ohare/en/home/Pages/default.aspx",
        "wikipedia_link": "http://en.wikipedia.org/wiki/O'Hare_International_Airport",
        "keywords": "CHI, Orchard Place"
    },
    'YYZ':   {
        "id": 1990,
        "ident": "CYYZ",
        "type": "large_airport",
        "name": "Lester B. Pearson International Airport",
        "latitude_deg": 43.6772003174,
        "longitude_deg": -79.63059997559999,
        "elevation_ft": 569,
        "continent": "NA",
        "iso_country": "CA",
        "iso_region": "CA-ON",
        "municipality": "Toronto",
        "scheduled_service": "yes",
        "gps_code": "CYYZ",
        "iata_code": "YYZ",
        "local_code": "YYZ",
        "home_link": "http://www.gtaa.com/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Toronto_Pearson_International_Airport",
        "keywords": "YTO, Toronto International Airport, Malton"
    },
    'PHX':   {
        "id": 3772,
        "ident": "KPHX",
        "type": "large_airport",
        "name": "Phoenix Sky Harbor International Airport",
        "latitude_deg": 33.43429946899414,
        "longitude_deg": -112.01200103759766,
        "elevation_ft": 1135,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-AZ",
        "municipality": "Phoenix",
        "scheduled_service": "yes",
        "gps_code": "KPHX",
        "iata_code": "PHX",
        "local_code": "PHX",
        "home_link": "http://phoenix.gov/skyharborairport/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Phoenix_Sky_Harbor_International_Airport",
        "keywords": ""
    },
    'DFW':   {
        "id": 3488,
        "ident": "KDFW",
        "type": "large_airport",
        "name": "Dallas Fort Worth International Airport",
        "latitude_deg": 32.89680099487305,
        "longitude_deg": -97.03800201416016,
        "elevation_ft": 607,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-TX",
        "municipality": "Dallas-Fort Worth",
        "scheduled_service": "yes",
        "gps_code": "KDFW",
        "iata_code": "DFW",
        "local_code": "DFW",
        "home_link": "http://www.dfwairport.com/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Dallas-Fort_Worth_International_Airport",
        "keywords": "QDF"
    },
    'LAX':   {
        "id": 3632,
        "ident": "KLAX",
        "type": "large_airport",
        "name": "Los Angeles International Airport",
        "latitude_deg": 33.94250107,
        "longitude_deg": -118.4079971,
        "elevation_ft": 125,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-CA",
        "municipality": "Los Angeles",
        "scheduled_service": "yes",
        "gps_code": "KLAX",
        "iata_code": "LAX",
        "local_code": "LAX",
        "home_link": "http://www.iflylax.com/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Los_Angeles_International_Airport",
        "keywords": ""
    },
    'AMS':   {
        "id": 2513,
        "ident": "EHAM",
        "type": "large_airport",
        "name": "Amsterdam Airport Schiphol",
        "latitude_deg": 52.3086013794,
        "longitude_deg": 4.763889789579999,
        "elevation_ft": -11,
        "continent": "EU",
        "iso_country": "NL",
        "iso_region": "NL-NH",
        "municipality": "Amsterdam",
        "scheduled_service": "yes",
        "gps_code": "EHAM",
        "iata_code": "AMS",
        "local_code": "",
        "home_link": "http://www.schiphol.nl/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Amsterdam_Schiphol_Airport",
        "keywords": ""
    },
    'LUX':   {
        "id": 2563,
        "ident": "ELLX",
        "type": "large_airport",
        "name": "Luxembourg-Findel International Airport",
        "latitude_deg": 49.6233333,
        "longitude_deg": 6.2044444,
        "elevation_ft": 1234,
        "continent": "EU",
        "iso_country": "LU",
        "iso_region": "LU-L",
        "municipality": "Luxembourg",
        "scheduled_service": "yes",
        "gps_code": "ELLX",
        "iata_code": "LUX",
        "local_code": "",
        "home_link": "http://www.lux-airport.lu/en/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Luxembourg-Findel_International_Airport",
        "keywords": ""
    },
    'LHR':   {
        "id": 2434,
        "ident": "EGLL",
        "type": "large_airport",
        "name": "London Heathrow Airport",
        "latitude_deg": 51.4706,
        "longitude_deg": -0.461941,
        "elevation_ft": 83,
        "continent": "EU",
        "iso_country": "GB",
        "iso_region": "GB-ENG",
        "municipality": "London",
        "scheduled_service": "yes",
        "gps_code": "EGLL",
        "iata_code": "LHR",
        "local_code": "",
        "home_link": "http://www.heathrowairport.com/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/London_Heathrow_Airport",
        "keywords": "LON, Londres"
    },
    'LGW':   {
        "id": 2429,
        "ident": "EGKK",
        "type": "large_airport",
        "name": "London Gatwick Airport",
        "latitude_deg": 51.148101806640625,
        "longitude_deg": -0.19027799367904663,
        "elevation_ft": 202,
        "continent": "EU",
        "iso_country": "GB",
        "iso_region": "GB-ENG",
        "municipality": "London",
        "scheduled_service": "yes",
        "gps_code": "EGKK",
        "iata_code": "LGW",
        "local_code": "",
        "home_link": "http://www.gatwickairport.com/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/London_Gatwick_Airport",
        "keywords": "LON, Crawley, Charlwood"
    },
    'SPJC': {
        "id": 6217,
        "ident": "SPIM",
        "type": "large_airport",
        "name": "Jorge Chávez International Airport",
        "latitude_deg": -12.0219,
        "longitude_deg": -77.114305,
        "elevation_ft": 113,
        "continent": "SA",
        "iso_country": "PE",
        "iso_region": "PE-LIM",
        "municipality": "Lima",
        "scheduled_service": "yes",
        "gps_code": "SPJC",
        "iata_code": "LIM",
        "local_code": "",
        "home_link": "http://www.lap.com.pe/",
        "wikipedia_link": "https://en.wikipedia.org/wiki/Jorge_Ch%C3%A1vez_International_Airport",
        "keywords": "SPIM"
    },
    'CUZ':   {
        "id": 6243,
        "ident": "SPZO",
        "type": "large_airport",
        "name": "Alejandro Velasco Astete International Airport",
        "latitude_deg": -13.535699844400002,
        "longitude_deg": -71.9387969971,
        "elevation_ft": 10860,
        "continent": "SA",
        "iso_country": "PE",
        "iso_region": "PE-CUS",
        "municipality": "Cusco",
        "scheduled_service": "yes",
        "gps_code": "SPZO",
        "iata_code": "CUZ",
        "local_code": "",
        "home_link": "http://www.corpac.gob.pe/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Alejandro_Velasco_Astete_International_Airport",
        "keywords": ""
    },
    'MIA':   {
        "id": 3685,
        "ident": "KMIA",
        "type": "large_airport",
        "name": "Miami International Airport",
        "latitude_deg": 25.79319953918457,
        "longitude_deg": -80.29060363769531,
        "elevation_ft": 8,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-FL",
        "municipality": "Miami",
        "scheduled_service": "yes",
        "gps_code": "KMIA",
        "iata_code": "MIA",
        "local_code": "MIA",
        "home_link": "http://www.miami-airport.com/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Miami_International_Airport",
        "keywords": "MFW, South Florida"
    },
    'SLC':   {
        "id": 3887,
        "ident": "KSLC",
        "type": "large_airport",
        "name": "Salt Lake City International Airport",
        "latitude_deg": 40.78839874267578,
        "longitude_deg": -111.97799682617188,
        "elevation_ft": 4227,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-UT",
        "municipality": "Salt Lake City",
        "scheduled_service": "yes",
        "gps_code": "KSLC",
        "iata_code": "SLC",
        "local_code": "SLC",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Salt_Lake_City_International_Airport",
        "keywords": ""
    },
    'JFK':   {
        "id": 3622,
        "ident": "KJFK",
        "type": "large_airport",
        "name": "John F Kennedy International Airport",
        "latitude_deg": 40.63980103,
        "longitude_deg": -73.77890015,
        "elevation_ft": 13,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-NY",
        "municipality": "New York",
        "scheduled_service": "yes",
        "gps_code": "KJFK",
        "iata_code": "JFK",
        "local_code": "JFK",
        "home_link": "http://www.panynj.gov/CommutingTravel/airports/html/kennedy.html",
        "wikipedia_link": "http://en.wikipedia.org/wiki/John_F._Kennedy_International_Airport",
        "keywords": "Manhattan, New York City, NYC, Idlewild"
    },
    'EWR':   {
        "id": 3521,
        "ident": "KEWR",
        "type": "large_airport",
        "name": "Newark Liberty International Airport",
        "latitude_deg": 40.692501068115234,
        "longitude_deg": -74.168701171875,
        "elevation_ft": 18,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-NJ",
        "municipality": "Newark",
        "scheduled_service": "yes",
        "gps_code": "KEWR",
        "iata_code": "EWR",
        "local_code": "EWR",
        "home_link": "http://www.panynj.gov/CommutingTravel/airports/html/newarkliberty.html",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Newark_Liberty_International_Airport",
        "keywords": "Manhattan, New York City, NYC"
    },
    'AUS':   {
        "id": 3386,
        "ident": "KAUS",
        "type": "large_airport",
        "name": "Austin Bergstrom International Airport",
        "latitude_deg": 30.194499969482422,
        "longitude_deg": -97.6698989868164,
        "elevation_ft": 542,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-TX",
        "municipality": "Austin",
        "scheduled_service": "yes",
        "gps_code": "KAUS",
        "iata_code": "AUS",
        "local_code": "AUS",
        "home_link": "http://www.ci.austin.tx.us/austinairport/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Austin-Bergstrom_International_Airport",
        "keywords": ""
    },
    'TPE':   {
        "id": 5528,
        "ident": "RCTP",
        "type": "large_airport",
        "name": "Taiwan Taoyuan International Airport",
        "latitude_deg": 25.0777,
        "longitude_deg": 121.233002,
        "elevation_ft": 106,
        "continent": "AS",
        "iso_country": "TW",
        "iso_region": "TW-TAO",
        "municipality": "Taipei",
        "scheduled_service": "yes",
        "gps_code": "RCTP",
        "iata_code": "TPE",
        "local_code": "",
        "home_link": "http://www.taoyuan-airport.com/",
        "wikipedia_link": "https://zh.wikipedia.org/wiki/%E8%87%BA%E7%81%A3%E6%A1%83%E5%9C%92%E5%9C%8B%E9%9A%9B%E6%A9%9F%E5%A0%B4",
        "keywords": "Taiwan Taoyuan International Airport, 臺灣桃園國際機場"
    },
    'BKK':   {
        "id": 28118,
        "ident": "VTBS",
        "type": "large_airport",
        "name": "Suvarnabhumi Airport",
        "latitude_deg": 13.681099891662598,
        "longitude_deg": 100.74700164794922,
        "elevation_ft": 5,
        "continent": "AS",
        "iso_country": "TH",
        "iso_region": "TH-10",
        "municipality": "Bangkok",
        "scheduled_service": "yes",
        "gps_code": "VTBS",
        "iata_code": "BKK",
        "local_code": "",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Suvarnabhumi_Airport",
        "keywords": ""
    },
    'VTE':   {
        "id": 26588,
        "ident": "VLVT",
        "type": "medium_airport",
        "name": "Wattay International Airport",
        "latitude_deg": 17.988300323500003,
        "longitude_deg": 102.56300354,
        "elevation_ft": 564,
        "continent": "AS",
        "iso_country": "LA",
        "iso_region": "LA-VT",
        "municipality": "Vientiane",
        "scheduled_service": "yes",
        "gps_code": "VLVT",
        "iata_code": "VTE",
        "local_code": "",
        "home_link": "http://www.vientianeairport.com/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Wattay_International_Airport",
        "keywords": ""
    },
    'HAN':   {
        "id": 26700,
        "ident": "VVNB",
        "type": "large_airport",
        "name": "Noi Bai International Airport",
        "latitude_deg": 21.221200942993164,
        "longitude_deg": 105.80699920654297,
        "elevation_ft": 39,
        "continent": "AS",
        "iso_country": "VN",
        "iso_region": "VN-15",
        "municipality": "Hanoi",
        "scheduled_service": "yes",
        "gps_code": "VVNB",
        "iata_code": "HAN",
        "local_code": "",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Noi_Bai_International_Airport",
        "keywords": "Noibai Airport, Sân bay Quốc tế Nội Bài"
    },
    'PNH': {
        "id": 26475,
        "ident": "VDPP",
        "type": "large_airport",
        "name": "Phnom Penh International Airport",
        "latitude_deg": 11.546600341796875,
        "longitude_deg": 104.84400177001953,
        "elevation_ft": 40,
        "continent": "AS",
        "iso_country": "KH",
        "iso_region": "KH-8",
        "municipality": "Phnom Penh",
        "scheduled_service": "yes",
        "gps_code": "VDPP",
        "iata_code": "PNH",
        "local_code": "",
        "home_link": "http://www.cambodia-airports.com/phnompenh/en/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Phnom_Penh_International_Airport",
        "keywords": "Pochentong International Airport"
    },
    'SIN': {
        "id": 26887,
        "ident": "WSSS",
        "type": "large_airport",
        "name": "Singapore Changi Airport",
        "latitude_deg": 1.35019,
        "longitude_deg": 103.994003,
        "elevation_ft": 22,
        "continent": "AS",
        "iso_country": "SG",
        "iso_region": "SG-04",
        "municipality": "Singapore",
        "scheduled_service": "yes",
        "gps_code": "WSSS",
        "iata_code": "SIN",
        "local_code": "",
        "home_link": "http://www.changiairport.com/",
        "wikipedia_link": "https://en.wikipedia.org/wiki/Singapore_Changi_Airport",
        "keywords": ""
    },
    'MNL': {
        "id": 5689,
        "ident": "RPLL",
        "type": "large_airport",
        "name": "Ninoy Aquino International Airport",
        "latitude_deg": 14.5086,
        "longitude_deg": 121.019997,
        "elevation_ft": 75,
        "continent": "AS",
        "iso_country": "PH",
        "iso_region": "PH-U-A",
        "municipality": "Manila",
        "scheduled_service": "yes",
        "gps_code": "RPLL",
        "iata_code": "MNL",
        "local_code": "",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Ninoy_Aquino_International_Airport",
        "keywords": "Manila International Airport"
    },
    'CEB': {
        "id": 5742,
        "ident": "RPVM",
        "type": "large_airport",
        "name": "Mactan Cebu International Airport",
        "latitude_deg": 10.307499885559,
        "longitude_deg": 123.97899627686,
        "elevation_ft": 31,
        "continent": "AS",
        "iso_country": "PH",
        "iso_region": "PH-CEB",
        "municipality": "Lapu-Lapu City",
        "scheduled_service": "yes",
        "gps_code": "RPVM",
        "iata_code": "CEB",
        "local_code": "",
        "home_link": "http://www.mactan-cebuairport.com.ph/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Mactan-Cebu_International_Airport",
        "keywords": ""
    },
    'PPS': {
        "id": 5744,
        "ident": "RPVP",
        "type": "medium_airport",
        "name": "Puerto Princesa Airport",
        "latitude_deg": 9.742119789123535,
        "longitude_deg": 118.75900268554688,
        "elevation_ft": 71,
        "continent": "AS",
        "iso_country": "PH",
        "iso_region": "PH-PLW",
        "municipality": "Puerto Princesa City",
        "scheduled_service": "yes",
        "gps_code": "RPVP",
        "iata_code": "PPS",
        "local_code": "",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Puerto_Princesa_Airport",
        "keywords": ""
    },
    'DPS': {
        "id": 26751,
        "ident": "WADD",
        "type": "large_airport",
        "name": "Ngurah Rai (Bali) International Airport",
        "latitude_deg": -8.7481698989868,
        "longitude_deg": 115.16699981689,
        "elevation_ft": 14,
        "continent": "AS",
        "iso_country": "ID",
        "iso_region": "ID-BA",
        "municipality": "Denpasar-Bali Island",
        "scheduled_service": "yes",
        "gps_code": "WADD",
        "iata_code": "DPS",
        "local_code": "",
        "home_link": "http://www.angkasapura1.co.id/eng/location/bali.htm",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Ngurah_Rai_Airport",
        "keywords": "WRRR"
    },
    'SFO': {
        "id": 3878,
        "ident": "KSFO",
        "type": "large_airport",
        "name": "San Francisco International Airport",
        "latitude_deg": 37.61899948120117,
        "longitude_deg": -122.375,
        "elevation_ft": 13,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-CA",
        "municipality": "San Francisco",
        "scheduled_service": "yes",
        "gps_code": "KSFO",
        "iata_code": "SFO",
        "local_code": "SFO",
        "home_link": "http://www.flysfo.com/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/San_Francisco_International_Airport",
        "keywords": "QSF, QBA"
    },
    'LAS':   {
        "id": 3631,
        "ident": "KLAS",
        "type": "large_airport",
        "name": "McCarran International Airport",
        "latitude_deg": 36.08010101,
        "longitude_deg": -115.1520004,
        "elevation_ft": 2181,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-NV",
        "municipality": "Las Vegas",
        "scheduled_service": "yes",
        "gps_code": "KLAS",
        "iata_code": "LAS",
        "local_code": "LAS",
        "home_link": "http://www.mccarran.com/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/McCarran_International_Airport",
        "keywords": ""
    },
    'DBV': {
        "id": 3984,
        "ident": "LDDU",
        "type": "medium_airport",
        "name": "Dubrovnik Airport",
        "latitude_deg": 42.5614013671875,
        "longitude_deg": 18.268199920654297,
        "elevation_ft": 527,
        "continent": "EU",
        "iso_country": "HR",
        "iso_region": "HR-19",
        "municipality": "Dubrovnik",
        "scheduled_service": "yes",
        "gps_code": "LDDU",
        "iata_code": "DBV",
        "local_code": "",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Dubrovnik_Airport",
        "keywords": ""
    },
    'CUN': {
        "id": 4762,
        "ident": "MMUN",
        "type": "large_airport",
        "name": "Cancún International Airport",
        "latitude_deg": 21.036500930800003,
        "longitude_deg": -86.8770980835,
        "elevation_ft": 22,
        "continent": "NA",
        "iso_country": "MX",
        "iso_region": "MX-ROO",
        "municipality": "Cancún",
        "scheduled_service": "yes",
        "gps_code": "MMUN",
        "iata_code": "CUN",
        "local_code": "",
        "home_link": "http://www.asur.com.mx/asur/ingles/aeropuertos/cancun/cancun.asp",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Canc%C3%BAn_International_Airport",
        "keywords": ""
    },
    'TZA':   {
        "id": 42215,
        "ident": "BZ-TZA",
        "type": "medium_airport",
        "name": "Belize City Municipal Airport",
        "latitude_deg": 17.516389846801758,
        "longitude_deg": -88.19444274902344,
        "elevation_ft": 16,
        "continent": "NA",
        "iso_country": "BZ",
        "iso_region": "BZ-BZ",
        "municipality": "Belize City",
        "scheduled_service": "yes",
        "gps_code": "",
        "iata_code": "TZA",
        "local_code": "",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Belize_City_Municipal_Airport",
        "keywords": ""
    },
    'SJO':   {
        "id": 4810,
        "ident": "MROC",
        "type": "medium_airport",
        "name": "Juan Santamaria International Airport",
        "latitude_deg": 9.993860244750977,
        "longitude_deg": -84.20880126953125,
        "elevation_ft": 3021,
        "continent": "NA",
        "iso_country": "CR",
        "iso_region": "CR-A",
        "municipality": "San Jose",
        "scheduled_service": "yes",
        "gps_code": "MROC",
        "iata_code": "SJO",
        "local_code": "",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Juan_Santamar%C3%ADa_International_Airport",
        "keywords": ""
    },
    'SAL':   {
        "id": 4820,
        "ident": "MSLP",
        "type": "large_airport",
        "name": "Monseñor Óscar Arnulfo Romero International Airport",
        "latitude_deg": 13.4409,
        "longitude_deg": -89.055702,
        "elevation_ft": 101,
        "continent": "NA",
        "iso_country": "SV",
        "iso_region": "SV-PA",
        "municipality": "San Salvador (San Luis Talpa)",
        "scheduled_service": "yes",
        "gps_code": "MSLP",
        "iata_code": "SAL",
        "local_code": "",
        "home_link": "",
        "wikipedia_link": "https://en.wikipedia.org/wiki/Monse%C3%B1or_%C3%93scar_Arnulfo_Romero_International_Airport",
        "keywords": ""
    },
    'PTY':   {
        "id": 4793,
        "ident": "MPTO",
        "type": "large_airport",
        "name": "Tocumen International Airport",
        "latitude_deg": 9.0713596344,
        "longitude_deg": -79.3834991455,
        "elevation_ft": 135,
        "continent": "NA",
        "iso_country": "PA",
        "iso_region": "PA-8",
        "municipality": "Tocumen",
        "scheduled_service": "yes",
        "gps_code": "MPTO",
        "iata_code": "PTY",
        "local_code": "",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Tocumen_International_Airport",
        "keywords": "La Joya No 1"
    },
    'MSY':   {
        "id": 3711,
        "ident": "KMSY",
        "type": "large_airport",
        "name": "Louis Armstrong New Orleans International Airport",
        "latitude_deg": 29.99340057373047,
        "longitude_deg": -90.25800323486328,
        "elevation_ft": 4,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-LA",
        "municipality": "New Orleans",
        "scheduled_service": "yes",
        "gps_code": "KMSY",
        "iata_code": "MSY",
        "local_code": "MSY",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Louis_Armstrong_New_Orleans_International_Airport",
        "keywords": ""
    },
    'PDX':   {
        "id": 3768,
        "ident": "KPDX",
        "type": "large_airport",
        "name": "Portland International Airport",
        "latitude_deg": 45.58869934,
        "longitude_deg": -122.5979996,
        "elevation_ft": 31,
        "continent": "NA",
        "iso_country": "US",
        "iso_region": "US-OR",
        "municipality": "Portland",
        "scheduled_service": "yes",
        "gps_code": "KPDX",
        "iata_code": "PDX",
        "local_code": "PDX",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Portland_International_Airport",
        "keywords": ""
    },
    'BOG':   {
        "id": 6104,
        "ident": "SKBO",
        "type": "large_airport",
        "name": "El Dorado International Airport",
        "latitude_deg": 4.70159,
        "longitude_deg": -74.1469,
        "elevation_ft": 8361,
        "continent": "SA",
        "iso_country": "CO",
        "iso_region": "CO-CUN",
        "municipality": "Bogota",
        "scheduled_service": "yes",
        "gps_code": "SKBO",
        "iata_code": "BOG",
        "local_code": "BOG",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/El_Dorado_International_Airport",
        "keywords": ""
    },
    'MDE':   {
        "id": 6158,
        "ident": "SKRG",
        "type": "medium_airport",
        "name": "Jose Maria Córdova International Airport",
        "latitude_deg": 6.16454,
        "longitude_deg": -75.4231,
        "elevation_ft": 6955,
        "continent": "SA",
        "iso_country": "CO",
        "iso_region": "CO-ANT",
        "municipality": "Medellín",
        "scheduled_service": "yes",
        "gps_code": "SKRG",
        "iata_code": "MDE",
        "local_code": "MDE",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Jos%C3%A9_Mar%C3%ADa_C%C3%B3rdova_International_Airport",
        "keywords": ""
    },
    'CTG': {
        "id": 6109,
        "ident": "SKCG",
        "type": "medium_airport",
        "name": "Rafael Nuñez International Airport",
        "latitude_deg": 10.4424,
        "longitude_deg": -75.513,
        "elevation_ft": 4,
        "continent": "SA",
        "iso_country": "CO",
        "iso_region": "CO-BOL",
        "municipality": "Cartagena",
        "scheduled_service": "yes",
        "gps_code": "SKCG",
        "iata_code": "CTG",
        "local_code": "CTG",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Rafael_N%C3%BA%C3%B1ez_International_Airport",
        "keywords": ""
    },
    'PVG':   {
        "id": 27223,
        "ident": "ZSPD",
        "type": "large_airport",
        "name": "Shanghai Pudong International Airport",
        "latitude_deg": 31.143400192260742,
        "longitude_deg": 121.80500030517578,
        "elevation_ft": 13,
        "continent": "AS",
        "iso_country": "CN",
        "iso_region": "CN-31",
        "municipality": "Shanghai",
        "scheduled_service": "yes",
        "gps_code": "ZSPD",
        "iata_code": "PVG",
        "local_code": "",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Shanghai_Pudong_International_Airport",
        "keywords": ""
    },
    'CNX':   {
        "id": 26647,
        "ident": "VTCC",
        "type": "large_airport",
        "name": "Chiang Mai International Airport",
        "latitude_deg": 18.766799926799997,
        "longitude_deg": 98.962600708,
        "elevation_ft": 1036,
        "continent": "AS",
        "iso_country": "TH",
        "iso_region": "TH-50",
        "municipality": "Chiang Mai",
        "scheduled_service": "yes",
        "gps_code": "VTCC",
        "iata_code": "CNX",
        "local_code": "",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Chiang_Mai_International_Airport",
        "keywords": ""
    },
    'URT': {
        "id": 26665,
        "ident": "VTSB",
        "type": "medium_airport",
        "name": "Surat Thani Airport",
        "latitude_deg": 9.13259983063,
        "longitude_deg": 99.135597229,
        "elevation_ft": 20,
        "continent": "AS",
        "iso_country": "TH",
        "iso_region": "TH-84",
        "municipality": "Surat Thani",
        "scheduled_service": "yes",
        "gps_code": "VTSB",
        "iata_code": "URT",
        "local_code": "",
        "home_link": "",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Surat_Thani_Airport",
        "keywords": ""
    },
    'COK':   {
        "id": 26609,
        "ident": "VOCI",
        "type": "large_airport",
        "name": "Cochin International Airport",
        "latitude_deg": 10.152,
        "longitude_deg": 76.401901,
        "elevation_ft": 30,
        "continent": "AS",
        "iso_country": "IN",
        "iso_region": "IN-KL",
        "municipality": "Kochi",
        "scheduled_service": "yes",
        "gps_code": "VOCI",
        "iata_code": "COK",
        "local_code": "",
        "home_link": "http://www.cochin-airport.com/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Cochin_International_Airport",
        "keywords": "Cochin"
    },
    'DMK': {
        "id": 26638,
        "ident": "VTBD",
        "type": "large_airport",
        "name": "Don Mueang International Airport",
        "latitude_deg": 13.9125995636,
        "longitude_deg": 100.607002258,
        "elevation_ft": 9,
        "continent": "AS",
        "iso_country": "TH",
        "iso_region": "TH-10",
        "municipality": "Bangkok",
        "scheduled_service": "yes",
        "gps_code": "VTBD",
        "iata_code": "DMK",
        "local_code": "",
        "home_link": "http://www2.airportthai.co.th/airportnew/bangkok/index.asp?lang=en",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Don_Mueang_International_Airport",
        "keywords": "Old Bangkok International Airport, Don Muang Royal Thai Air Force Base"
    },
    'BLR': {
        "id": 35145,
        "ident": "VOBL",
        "type": "large_airport",
        "name": "Kempegowda International Airport",
        "latitude_deg": 13.1979,
        "longitude_deg": 77.706299,
        "elevation_ft": 3000,
        "continent": "AS",
        "iso_country": "IN",
        "iso_region": "IN-KA",
        "municipality": "Bangalore",
        "scheduled_service": "yes",
        "gps_code": "VOBL",
        "iata_code": "BLR",
        "local_code": "",
        "home_link": "http://www.bengaluruairport.com/home/home.jspx",
        "wikipedia_link": "https://en.wikipedia.org/wiki/Kempegowda_International_Airport",
        "keywords": ""
    },
    'DOH':   {
        "id": 44686,
        "ident": "QA-0001",
        "type": "large_airport",
        "name": "Hamad International Airport",
        "latitude_deg": 25.273056,
        "longitude_deg": 51.608056,
        "elevation_ft": 13,
        "continent": "AS",
        "iso_country": "QA",
        "iso_region": "QA-DA",
        "municipality": "Doha",
        "scheduled_service": "yes",
        "gps_code": "OTHH",
        "iata_code": "DOH",
        "local_code": "",
        "home_link": "http://dohahamadairport.com/",
        "wikipedia_link": "http://en.wikipedia.org/wiki/Hamad_International_Airport",
        "keywords": "New Doha International Airport"
    },
};

function toLatLng(airport, a) {
    if (airport == undefined) {
        console.log("undefined airport!", a)
        return {
            'lat': 0,
            'lng': 0,
            'name': 'undefined'
        }
    }
    return {
        'lat': airport.latitude_deg,
        'lng': airport.longitude_deg,
        'name': airport.name,
    }
}

const FlightMap = connect(
    state => ( {
        flightPaths: state.routes.map(( route ) => [
            { ...toLatLng(AIRPORT_COORDINATES[ route.fromAirport], route.fromAirport) },
            { ...toLatLng(AIRPORT_COORDINATES[ route.toAirport ], route.toAirport) },
        ]),
    } ),
)(Map)



export default FlightMap